<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wecome gmail</name>
   <tag></tag>
   <elementGuidId>ca61eae2-52a6-489c-9174-2bd98cc0f2ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'vijaykumar220997@gmail.com')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5b39c98-f27a-4af1-9f24-d37887bba0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer/info</value>
      <webElementGuid>4b2a52a1-a9e4-444e-a540-8a5a33984682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>89ced86f-0cc0-4ae7-af9f-310283cd8203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>vijaykumar220997@gmail.com</value>
      <webElementGuid>fc46cf6c-53e9-4529-ac52-cb9c7f90c6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;header-links-wrapper&quot;]/div[@class=&quot;header-links&quot;]/ul[1]/li[1]/a[@class=&quot;account&quot;]</value>
      <webElementGuid>8e2556ba-66ea-4f27-b836-cf38ac3da454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'vijaykumar220997@gmail.com')]</value>
      <webElementGuid>e9bf6a91-adf5-4e13-a04b-855e9ee6f68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>40d29ded-4a94-47cb-aad7-e424a5084fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping cart'])[1]/preceding::a[2]</value>
      <webElementGuid>e519f77f-cabf-4a7e-a28f-06c246a5d46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='vijaykumar220997@gmail.com']/parent::*</value>
      <webElementGuid>f816af87-6e7f-4e02-a723-b0738682874e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer/info')]</value>
      <webElementGuid>781f116e-e200-441e-a7c9-f5b82cf83fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>8ee150d8-54a9-4146-97b3-2389a0a41c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer/info' and (text() = 'vijaykumar220997@gmail.com' or . = 'vijaykumar220997@gmail.com')]</value>
      <webElementGuid>2704b0b5-a3f9-4e25-b3cb-a7fdb8bbfdcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
